### ISSUE TITLE
Crash during unit test

### ISSUE THREAD

**Issue by abroxos** [iut-ibk/DynaMind-ToolBox#254]
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.

**Comment by abroxos** [comment]
@christianurich: Please check gdal unit tests

**Comment by christianurich** [comment]
can't work out what the problem is (OS X and Linux are fine) any idea?

**Comment by abroxos** [comment]
Running main() from gtest_main.cc
[==========] Running 42 tests from 7 test cases.
[----------] Global test environment set-up.
[----------] 8 tests from TestGDALModules
[ RUN      ] TestGDALModules.GDAL_ADVANCE_API_TEST
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
[       OK ] TestGDALModules.GDAL_ADVANCE_API_TEST (1773 ms)
[ RUN      ] TestGDALModules.TestInsertSpeed_DM
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
[       OK ] TestGDALModules.TestInsertSpeed_DM (620 ms)
[ RUN      ] TestGDALModules.TestInsertSpeed
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
[       OK ] TestGDALModules.TestInsertSpeed (780 ms)
[ RUN      ] TestGDALModules.ConnectionTest
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
[       OK ] TestGDALModules.ConnectionTest (811 ms)
[ RUN      ] TestGDALModules.BranchingTest
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
C:\Users\c815\Desktop\DynaMind\src\unit-test\testgdalmodules.cpp(164): error: Value of: number
  Actual: 2000
Expected: components.getFeatureCount()
Which is: 1000
C:\Users\c815\Desktop\DynaMind\src\unit-test\testgdalmodules.cpp(164): error: Value of: number
  Actual: 2000
Expected: components.getFeatureCount()
Which is: 1000
[  FAILED  ] TestGDALModules.BranchingTest (918 ms)
[ RUN      ] TestGDALModules.UpdateTest
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
[       OK ] TestGDALModules.UpdateTest (726 ms)
[ RUN      ] TestGDALModules.BranchModify
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
C:\Users\c815\Desktop\DynaMind\src\unit-test\testgdalmodules.cpp(233): error: Value of: number
  Actual: 1000
Expected: components.getFeatureCount()
Which is: 0
C:\Users\c815\Desktop\DynaMind\src\unit-test\testgdalmodules.cpp(233): error: Value of: number
  Actual: 1000
Expected: components.getFeatureCount()
Which is: 0
[  FAILED  ] TestGDALModules.BranchModify (852 ms)
[ RUN      ] TestGDALModules.WriteAttributes
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
ERROR	 Mi MÃ¤r 18 14:41:14 2015| Attribute typer STRINGVECTOR is currently not supported
ERROR	 Mi MÃ¤r 18 14:41:14 2015| 3
[       OK ] TestGDALModules.WriteAttributes (926 ms)
[----------] 8 tests from TestGDALModules (7407 ms total)

[----------] 6 tests from TestGDALPython
[ RUN      ] TestGDALPython.LoadPython
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
<pydynamind.ViewContainer; proxy of <Swig Object of type 'DM::ViewContainer *' at 0x000000406AD18150> >
[       OK ] TestGDALPython.LoadPython (4158 ms)
[ RUN      ] TestGDALPython.PythonConnectionTest
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
C:\Users\c815\Desktop\DynaMind\src\unit-test\testgdalpython.cpp(87): error: Value of: 2*number
  Actual: 2000
Expected: components.getFeatureCount()
Which is: 0
C:\Users\c815\Desktop\DynaMind\src\unit-test\testgdalpython.cpp(87): error: Value of: 2*number
  Actual: 2000
Expected: components.getFeatureCount()
Which is: 0
[  FAILED  ] TestGDALPython.PythonConnectionTest (850 ms)
[ RUN      ] TestGDALPython.PythonReadTest
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
ERROR	 Mi MÃ¤r 18 14:41:20 2015| System is not valid
C:\Users\c815\Desktop\DynaMind\src\unit-test\testgdalpython.cpp(126): error: Value of: number
  Actual: 0
Expected: number1
Which is: 1000
C:\Users\c815\Desktop\DynaMind\src\unit-test\testgdalpython.cpp(126): error: Value of: number
  Actual: 0
Expected: number1
Which is: 1000
[  FAILED  ] TestGDALPython.PythonReadTest (753 ms)
[ RUN      ] TestGDALPython.PythonModifyTest
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
Traceback (most recent call last):
  File "C:/Users/c815/Desktop/DynaMind/build/PythonModules/scripts\TestModules\create_gdal_component.py", line 58, in run
    f = self.n.create_feature()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5667, in create_feature
    self.register_layer()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5695, in register_layer
    self.__ogr_layer = self.__ds.GetLayerByName(table_name)
AttributeError: 'NoneType' object has no attribute 'GetLayerByName'
Traceback (most recent call last):
  File "C:/Users/c815/Desktop/DynaMind/build/PythonModules/scripts\TestModules\create_gdal_advanced_api.py", line 52, in run
    f = self.__container.create_feature()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5667, in create_feature
    self.register_layer()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5695, in register_layer
    self.__ogr_layer = self.__ds.GetLayerByName(table_name)
AttributeError: 'NoneType' object has no attribute 'GetLayerByName'
Traceback (most recent call last):
  File "C:/Users/c815/Desktop/DynaMind/build/PythonModules/scripts\TestModules\create_gdal_advanced_api.py", line 52, in run
    f = self.__container.create_feature()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5667, in create_feature
    self.register_layer()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5695, in register_layer
    self.__ogr_layer = self.__ds.GetLayerByName(table_name)
AttributeError: 'NoneType' object has no attribute 'GetLayerByName'
Traceback (most recent call last):
  File "C:/Users/c815/Desktop/DynaMind/build/PythonModules/scripts\TestModules\create_gdal_advanced_api.py", line 52, in run
    f = self.__container.create_feature()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5667, in create_feature
    self.register_layer()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5695, in register_layer
    self.__ogr_layer = self.__ds.GetLayerByName(table_name)
AttributeError: 'NoneType' object has no attribute 'GetLayerByName'
Traceback (most recent call last):
  File "C:/Users/c815/Desktop/DynaMind/build/PythonModules/scripts\TestModules\read_gdal_advanced_api.py", line 52, in run
    self.__container.reset_reading()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5738, in reset_reading
    self.register_layer()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5695, in register_layer
    self.__ogr_layer = self.__ds.GetLayerByName(table_name)
AttributeError: 'NoneType' object has no attribute 'GetLayerByName'
Traceback (most recent call last):
  File "C:/Users/c815/Desktop/DynaMind/build/PythonModules/scripts\TestModules\create_gdal_advanced_api.py", line 52, in run
    f = self.__container.create_feature()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5667, in create_feature
    self.register_layer()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5695, in register_layer
    self.__ogr_layer = self.__ds.GetLayerByName(table_name)
AttributeError: 'NoneType' object has no attribute 'GetLayerByName'
Traceback (most recent call last):
  File "C:/Users/c815/Desktop/DynaMind/build/PythonModules/scripts\TestModules\modify_gdal_advanced_api.py", line 44, in run
    self.__container.reset_reading()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5738, in reset_reading
    self.register_layer()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5695, in register_layer
    self.__ogr_layer = self.__ds.GetLayerByName(table_name)
AttributeError: 'NoneType' object has no attribute 'GetLayerByName'
Traceback (most recent call last):
  File "C:/Users/c815/Desktop/DynaMind/build/PythonModules/scripts\TestModules\read_gdal_advanced_api.py", line 52, in run
    self.__container.reset_reading()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", line 5738, in reset_reading
    self.register_layer()
  File "C:\Users\c815\Desktop\DynaMind\build\pydynamind.py", ERROR	 Mi MÃ¤r 18 14:41:21 2015| System is not valid
C:\Users\c815\Desktop\DynaMind\src\unit-test\testgdalpython.cpp(172): error: Value of: number
  Actual: 0
Expected: 3*number1
Which is: 3000C:\Users\c815\Desktop\DynaMind\src\unit-test\testgdalpython.cpp(172): error: Value of: number
  Actual: 0
Expected: 3*number1
Which is: 3000

[  FAILED  ] TestGDALPython.PythonModifyTest (1132 ms)
[ RUN      ] TestGDALPython.PythonLinks
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
unknown file: error: C++ exception with description "Unknown exception" thrown in the test body.unknown file: error: C++ exception with description "Unknown exception" thrown in the test body.

[  FAILED  ] TestGDALPython.PythonLinks (766 ms)
[ RUN      ] TestGDALPython.AdvancedDataTypes
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
[       OK ] TestGDALPython.AdvancedDataTypes (628 ms)
[----------] 6 tests from TestGDALPython (8287 ms total)

[----------] 1 test from TestModules
[ RUN      ] TestModules.setParameterInModule
[       OK ] TestModules.setParameterInModule (62 ms)
[----------] 1 test from TestModules (62 ms total)

[----------] 1 test from TestPython
[ RUN      ] TestPython.redirectPythonOutput
[       OK ] TestPython.redirectPythonOutput (1 ms)
[----------] 1 test from TestPython (1 ms total)

[----------] 8 tests from TestSimulation
[ RUN      ] TestSimulation.testMemory
[       OK ] TestSimulation.testMemory (4758 ms)
[ RUN      ] TestSimulation.addModuleToSimulationTest
[       OK ] TestSimulation.addModuleToSimulationTest (68 ms)
[ RUN      ] TestSimulation.loadModuleNativeTest
[       OK ] TestSimulation.loadModuleNativeTest (1 ms)
[ RUN      ] TestSimulation.repeatedRunTest
[       OK ] TestSimulation.repeatedRunTest (108 ms)
[ RUN      ] TestSimulation.linkedModulesTest
[       OK ] TestSimulation.linkedModulesTest (100 ms)
[ RUN      ] TestSimulation.linkedDynamicModules
[       OK ] TestSimulation.linkedDynamicModules (89 ms)
[ RUN      ] TestSimulation.LoopGroupTest
[       OK ] TestSimulation.LoopGroupTest (81 ms)
[ RUN      ] TestSimulation.linkedDynamicModulesOverGroups
[       OK ] TestSimulation.linkedDynamicModulesOverGroups (81 ms)
[----------] 8 tests from TestSimulation (5287 ms total)

[----------] 16 tests from TestSystem
[ RUN      ] TestSystem.DeleteComponentFromView
[       OK ] TestSystem.DeleteComponentFromView (8 ms)
[ RUN      ] TestSystem.ViewFilter
[       OK ] TestSystem.ViewFilter (0 ms)
[ RUN      ] TestSystem.memoryTest
[       OK ] TestSystem.memoryTest (0 ms)
[ RUN      ] TestSystem.RasterData_Flipped_Tset
[       OK ] TestSystem.RasterData_Flipped_Tset (276 ms)
[ RUN      ] TestSystem.RasterData_ValueTest
[       OK ] TestSystem.RasterData_ValueTest (68 ms)
[ RUN      ] TestSystem.cachetest
[       OK ] TestSystem.cachetest (0 ms)
[ RUN      ] TestSystem.sqlsuccessortest
[       OK ] TestSystem.sqlsuccessortest (11 ms)
[ RUN      ] TestSystem.SqlNodeTest
[       OK ] TestSystem.SqlNodeTest (9 ms)
[ RUN      ] TestSystem.SqlEdgeTest
[       OK ] TestSystem.SqlEdgeTest (62 ms)
[ RUN      ] TestSystem.SqlFaceOrder
[       OK ] TestSystem.SqlFaceOrder (54 ms)
[ RUN      ] TestSystem.SQLRasterdata
[       OK ] TestSystem.SQLRasterdata (71 ms)
[ RUN      ] TestSystem.SQLattributes
[       OK ] TestSystem.SQLattributes (45 ms)
[ RUN      ] TestSystem.AttributesInSystem
[       OK ] TestSystem.AttributesInSystem (0 ms)
[ RUN      ] TestSystem.SystemDBExInport
[       OK ] TestSystem.SystemDBExInport (98 ms)
[ RUN      ] TestSystem.SystemDBExInportSuccessor
[       OK ] TestSystem.SystemDBExInportSuccessor (8 ms)
[ RUN      ] TestSystem.SystemDBExInportAttributes
[       OK ] TestSystem.SystemDBExInportAttributes (28 ms)
[----------] 16 tests from TestSystem (738 ms total)

[----------] 2 tests from TestTBVectorData
[ RUN      ] TestTBVectorData.minNode
[       OK ] TestTBVectorData.minNode (4 ms)
[ RUN      ] TestTBVectorData.AngelBetweenVectors
[       OK ] TestTBVectorData.AngelBetweenVectors (0 ms)
[----------] 2 tests from TestTBVectorData (4 ms total)

[----------] Global test environment tear-down
[==========] 42 tests from 7 test cases ran. (21786 ms total)
[  PASSED  ] 36 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] TestGDALModules.BranchingTest
[  FAILED  ] TestGDALModules.BranchModify
[  FAILED  ] TestGDALPython.PythonConnectionTest
[  FAILED  ] TestGDALPython.PythonReadTest
[  FAILED  ] TestGDALPython.PythonModifyTest
[  FAILED  ] TestGDALPython.PythonLinks

 6 FAILED TESTS

**Comment by christianurich** [comment]
their was  weird problem with creating components. In windows per default nodes are created to fix the error
