### ISSUE TITLE
Windows build GDAL modules

### ISSUE THREAD

**Issue by christianurich** [iut-ibk/DynaMind-ToolBox#260]
@abroxos  Can you add SFCGAL http://oslandia.github.io/SFCGAL/ as windows dependency  to build the GDAL modules?

**Comment by abroxos** [comment]
Is already on my list :-)
Does it make sense to include this library in the core ?

**Comment by christianurich** [comment]
Great! You mean the SFCGAL code itself so it complies with DynaMind? I tried and failed.

**Comment by abroxos** [comment]
Ulli and I will take a look :+1:

**Comment by christianurich** [comment]
done will upload, just uploading binary including GDAL Modules
