### ISSUE TITLE
travis build fails because of linking error

### ISSUE THREAD

**Issue by christianurich** [iut-ibk/DynaMind-ToolBox#262]
See https://travis-ci.org/iut-ibk/DynaMind-ToolBox/jobs/56290565

[0m../../../output/libdynamindgui.a(dmmainwindow.cpp.o): In function `DMMainWindow::DMMainWindow(QWidget*)':
dmmainwindow.cpp:(.text+0x4223): undefined reference to `DM::PythonEnv::getInstance()'
dmmainwindow.cpp:(.text+0x4293): undefined reference to `DM::PythonEnv::addPythonPath(std::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
dmmainwindow.cpp:(.text+0x42c6): undefined reference to `DM::PythonEnv::addOverWriteStdCout()'
collect2: ld returned 1 exit status
make[2]: *** [output/dynamind-gui] Error 1
make[1]: *** [DynaMind-Gui/src/dynamind-modelbuilder/CMakeFiles/dynamind-gui.dir/all] Error 2
make: *** [all] Error 2

**Comment by chmuibk** [comment]
I do not have access to Jenkins. But this error is solved by setting PYTHON_EMBEDDING=ON

See this commit: https://github.com/iut-ibk/DynaMind-ToolBox/commit/53f491cde0ac715ca4931ab103cdb3939dfb101b
So the variable PYTHON_EMBEDDING was never checked in reality, now it is (and obviously it must be activated ...). This leaves for discussion:

- activate it by default (simplest solution)
- abandon it and demand python anyways.

**Comment by chmuibk** [comment]
I pushed a new CMakeLists.txt with PYTHON_EMBEDDING=ON by default. Any objections?

**Comment by christianurich** [comment]
works thanks!!!

**Comment by abroxos** [comment]
Thanks
