### ISSUE TITLE
Doc Functionality Groups

### ISSUE THREAD

**Issue by christianurich** [iut-ibk/DynaMind-ToolBox#265]
@abroxos I'm just working on the documentation for the groups and I have a few problems to work out what their functionality is

Just for my clarification:

ContainerGroup: only is useful in combination with GUI since the logic of replacing module parameter is part of the GUI?

ConditionalGroup: What are possible conditions and how is the attribute handle if their is more than one component in the view?

**Comment by chmuibk** [comment]
I'm using the ConditionalLoopgroup:

The condition is defined like: "VIEW.attribute = 1";
the modules in the group are executed if the condition is satisfied; hence you have to set the attribute outside and before the conditionalgroup and manipulate it inside of the group (in a module) to exit the loop at a give time.
as far as I can remember the conditions work only with numbers (not certain of that, needs verification)

**Comment by christianurich** [comment]
Thanks, do you know what happens if more than one component is in the view?

**Comment by abroxos** [comment]
I never used that group but i think only the first component is checked.

2015-04-10 9:45 GMT+02:00 Christian Urich <notifications@github.com>:

>  Thanks, do you know what happens if more than one component is in the
> view?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iut-ibk/DynaMind-ToolBox/issues/265#issuecomment-91469147>
> .
>



-- 
MSc Michael Mair
IUT Umwelttechnik - Institut für Infrastruktur
Universität Innsbruck
A-6020 Innsbruck; Technikerstrasse 13

Tel: +43 (0) 512 507 62129
M: michael.mair@uibk.ac.at
W: http://umwelttechnik.uibk.ac.at
W: http://michaelmair.eu

**Comment by christianurich** [comment]
I think  that answers my questions and for the loop implementation see #264
