### ISSUE TITLE
Windows Build and Compiler lock in in windows

### ISSUE THREAD

**Issue by christianurich** [iut-ibk/DynaMind-ToolBox#271]
@abroxos 

I tried to make a windows build that includes SFCGAL but failed. The problem is that vc 9.0 is getting really old and things start to fall apart. Particularly boost/cgal/sfcgal start to make problems in the newer version with compilers that don't support the new C++ standard.

Shifting to python 3.4 would help us to pump the compiler version to visual studio 10 which would hopefully resolve a lot of the problems but I have no idea how long that would take.

Any thoughts?

**Comment by chmuibk** [comment]
Are there any python modules needed / used at the moment?
I personally am not using Python Modules and am happy with a temporary "python construction area"

**Comment by christianurich** [comment]
I unfortunately have a few... that whole windows python dll thing is just nuts.... But I might have found a combination of library versions that with a few patches compile SFCGAL.

**Comment by christianurich** [comment]
OK I got it to work and it runs...

I had to patch SFCGAL to compile with vc9.0 this can be found [here](https://github.com/christianurich/SFCGAL)

- works only with CGAL 4.4 maybe 4.3 (not tested) otherwise C++11  compile errors
- boost 1.53 otherwise again C++11 compile errors
- I didn't end up embedding SFCGL in DynaMind since its cmake file needed to many fixes #260
