### ISSUE TITLE
GUI refreshment

### ISSUE THREAD

**Issue by christianurich** [iut-ibk/DynaMind-ToolBox#277]
Hi @abroxos @chmuibk

I have update the GUI to make it more useful for me. As the screen shot shows, the module description now also includes parameters, filters and the data stream. I pushed the version to the master. I can also include a few options to disable a few of the data and so it looks like the original version. Just let me know if you have any feedbacks or thoughts on this. 

![screen shot 2015-06-23 at 23 01 28](https://cloud.githubusercontent.com/assets/920819/8306544/11fbc864-19fc-11e5-940d-6beb5de9c60f.png)

**Comment by abroxos** [comment]
Good idea. I think we should just work some time with that and we will see if its necessary to add some options.

**Comment by attozeta** [comment]
That looks slick, but we have big performance problems with our models (probably because of the heavy redrawing that happens).

**Comment by christianurich** [comment]
That is interesting because on my machine it runs faster :-/ could you look int this?

**Comment by abroxos** [comment]
After some working with the "new" Gui i suggest to implement a option in "Menu bar" -> "View" -> "Switch model detail" ). The reason for that is that all our existing models are looking like a mess and are overloaded. Nobody can follow the workflow anymore, including myself.

**Comment by christianurich** [comment]
Fine with me. 

I’ll add this option.

**Comment by abroxos** [comment]
If you want Ulli can implement this option and have a look on the
perfomance.

2015-06-26 8:43 GMT+02:00 Christian Urich <notifications@github.com>:

>  Fine with me.
>
> I’ll add this option.
>
>
> > On 26 Jun 2015, at 16:42, Michael Mair <notifications@github.com> wrote:
> >
> > After some working with the "new" Gui i suggest to implement a option in
> "Menu bar" -> "View" -> "Switch model detail" ). The reason for that is
> that all our existing models are looking like a mess and are overloaded.
> Nobody can follow the workflow anymore, including myself.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/iut-ibk/DynaMind-ToolBox/issues/277#issuecomment-115546130
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iut-ibk/DynaMind-ToolBox/issues/277#issuecomment-115546578>
> .
>



-- 
MSc Michael Mair
IUT Umwelttechnik - Institut für Infrastruktur
Universität Innsbruck
A-6020 Innsbruck; Technikerstrasse 13

Tel: +43 (0) 512 507 62129
M: michael.mair@uibk.ac.at
W: http://umwelttechnik.uibk.ac.at
W: http://michaelmair.eu

**Comment by christianurich** [comment]
That would be great! 

The code should already be set up to simply disable the individual drawing  elements.

**Comment by chmuibk** [comment]
As it is the Toolbox GUI is unusable for me ... slow as hell. :( (Linux 64bit, qt 5.4.2)

**Comment by christianurich** [comment]
That is really annoying, particularly since it works so well on OS X.

**Comment by chmuibk** [comment]
I just did a git reset for the time beeing. No big deal.

**Comment by christianurich** [comment]
Are you guys using the qt5 version or qt4?

**Comment by chmuibk** [comment]
Im using qt5 (5.4.2). I can also run a test with qt4 ...

**Comment by christianurich** [comment]
I was hoping for the other way round. I also used qt5 and everything is fine

**Comment by attozeta** [comment]
I think the idea is great because it may give the user more information about a module's internals, without to always double-click each module (or right-clicking and "show data stream") however it is slow, as the paint() method does do much stuff. In particular constructing strings and blitting them onto the surface which is a costly operation. Now consider that qt decides itself when it wants to redraw (i.e. invoking paint) which happens e.g. if you resize the canvas and that's why we witness such a performance breakdown.

E.g. if you load a sufficiently large model and you scroll, paint() is obviously invoked for all the modules, i.e. modelnode.cpp's paint() is causing havoc. At the moment I investigate the idea of doing something similar on mouse-hover.

**Comment by christianurich** [comment]
Thanks for the fix!!!






On Thu, Jul 2, 2015 at 10:12 AM -0700, "attozeta" <notifications@github.com> wrote:












Closed #277.

**Comment by chmuibk** [comment]
Thanks. Working like a charm here.

One thing is: somethimes it is too much information and it makes model development a bit obfuscated. I don't know how to resolve that. Maybe some toggle per module (which is also saved in the .dyn file)?
![dyna](https://cloud.githubusercontent.com/assets/1876092/8495101/24401248-216b-11e5-85dd-148c84071436.png)
Any suggestions/comments?
